services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: mocs_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mocs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mocs_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: mocs_backend
    env_file:
      - .env
    environment:
      - DATABASE__URL=postgresql+asyncpg://admin:password123@postgres:5432/mocs_db
      - APP__DEBUG=true
      - WATCHFILES_IGNORE_PATHS=.venv/
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
